@startuml

title Bookstore ERD diagram\nexample

'[SECTION] Entities

entity "Entity01" as e01 {
    *e1_id : number <<generated>>
    --
    *name : text
    description : text
}

entity "Entity02" as e02 {
    *e2_id : number <<generated>>
    --
    *e1_id : number <<FK>>
    other_details : text
}

entity "Entity03" as e03 {
    *e3_id : number <<generated>>
    --
    e1_id : number <<FK>>
    other_details : text
}

entity "asd" {
    .. Simple Getter ..
    + getName()
    + getAddress()
    .. Some setter ..
    + setName()
    __ private data __
    int age
    -- encrypted --
    String password
}


'[SECTION] Relationships

e01 ||..o{ e02
e01 |o..o{ e03


'[SECTION] Skinparms

' Configure title appearance
' skinparam titleBorderRoundCorner 15
' skinparam titleBorderThickness 2
' skinparam titleBorderColor red
' skinparam titleBackgroundColor Aqua-CadetBlue

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho


@enduml