// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyThinkBook.Web.Data;

#nullable disable

namespace MyThinkBook.Web.Migrations.WmsDb
{
    [DbContext(typeof(WmsDbContext))]
    [Migration("20221228085329_20221228-1653")]
    partial class _202212281653
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("MyThinkBook.Domain.Wms.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("client_pk");

                    b.ToTable("client", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Stroman, Glover and Hane"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Adams, Wehner and Dach"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Hirthe, Breitenberg and Nienow"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Johns and Sons"
                        },
                        new
                        {
                            Id = "5",
                            Name = "Tromp, Boehm and Leuschke"
                        },
                        new
                        {
                            Id = "6",
                            Name = "Schuster Inc"
                        },
                        new
                        {
                            Id = "7",
                            Name = "Pouros Inc"
                        },
                        new
                        {
                            Id = "8",
                            Name = "Rowe, Bartell and Dare"
                        },
                        new
                        {
                            Id = "9",
                            Name = "Grady - Purdy"
                        },
                        new
                        {
                            Id = "10",
                            Name = "Zemlak and Sons"
                        },
                        new
                        {
                            Id = "11",
                            Name = "Shanahan Group"
                        },
                        new
                        {
                            Id = "12",
                            Name = "Mueller Group"
                        },
                        new
                        {
                            Id = "13",
                            Name = "Howe - Satterfield"
                        },
                        new
                        {
                            Id = "14",
                            Name = "Champlin, Ullrich and Muller"
                        },
                        new
                        {
                            Id = "15",
                            Name = "Beatty, Hane and Corwin"
                        },
                        new
                        {
                            Id = "16",
                            Name = "Daugherty Group"
                        },
                        new
                        {
                            Id = "17",
                            Name = "Lockman - Mayert"
                        },
                        new
                        {
                            Id = "18",
                            Name = "Rogahn Inc"
                        },
                        new
                        {
                            Id = "19",
                            Name = "Ziemann, Bayer and Bosco"
                        },
                        new
                        {
                            Id = "20",
                            Name = "Mosciski - Harris"
                        },
                        new
                        {
                            Id = "21",
                            Name = "Gibson Inc"
                        },
                        new
                        {
                            Id = "22",
                            Name = "Ankunding Group"
                        },
                        new
                        {
                            Id = "23",
                            Name = "Kihn - Rodriguez"
                        },
                        new
                        {
                            Id = "24",
                            Name = "Thiel - Braun"
                        },
                        new
                        {
                            Id = "25",
                            Name = "Collins Inc"
                        },
                        new
                        {
                            Id = "26",
                            Name = "Halvorson Inc"
                        },
                        new
                        {
                            Id = "27",
                            Name = "Smitham - Bayer"
                        },
                        new
                        {
                            Id = "28",
                            Name = "Leffler, Friesen and Schinner"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
