// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyThinkBook.Web.Data;

#nullable disable

namespace MyThinkBook.Web.Migrations.InvestmentDb
{
    [DbContext(typeof(InvestmentDbContext))]
    [Migration("20221220092248_20221220-1705")]
    partial class _202212201705
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("MyThinkBook.Web.Domain.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("instrument_pk");

                    b.ToTable("instrument", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Stock 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stock 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stock 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Stock 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Stock 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Stock 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Stock 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Stock 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Stock 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Stock 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Stock 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Stock 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Stock 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Stock 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Stock 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Stock 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Stock 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Stock 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Stock 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Stock 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Stock 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Stock 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Stock 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Stock 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Stock 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Stock 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Stock 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Stock 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Stock 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Stock 30"
                        });
                });

            modelBuilder.Entity("MyThinkBook.Web.Domain.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("portfolio_pk");

                    b.ToTable("portfolio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Portfolio 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Portfolio 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Portfolio 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Portfolio 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Portfolio 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Portfolio 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Portfolio 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Portfolio 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Portfolio 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Portfolio 10"
                        });
                });

            modelBuilder.Entity("MyThinkBook.Web.Domain.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("position_pk");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("position", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstrumentId = 26,
                            PortfolioId = 1,
                            Price = 274.59m,
                            Quantity = 587829m
                        },
                        new
                        {
                            Id = 2,
                            InstrumentId = 24,
                            PortfolioId = 1,
                            Price = 362.44m,
                            Quantity = 5126m
                        },
                        new
                        {
                            Id = 3,
                            InstrumentId = 12,
                            PortfolioId = 2,
                            Price = 331.10m,
                            Quantity = 589915m
                        },
                        new
                        {
                            Id = 4,
                            InstrumentId = 20,
                            PortfolioId = 2,
                            Price = 6.44m,
                            Quantity = 357208m
                        },
                        new
                        {
                            Id = 5,
                            InstrumentId = 9,
                            PortfolioId = 2,
                            Price = 333.11m,
                            Quantity = 88359m
                        },
                        new
                        {
                            Id = 6,
                            InstrumentId = 14,
                            PortfolioId = 2,
                            Price = 95.56m,
                            Quantity = 567796m
                        },
                        new
                        {
                            Id = 7,
                            InstrumentId = 17,
                            PortfolioId = 3,
                            Price = 132.53m,
                            Quantity = 126930m
                        },
                        new
                        {
                            Id = 8,
                            InstrumentId = 9,
                            PortfolioId = 3,
                            Price = 95.58m,
                            Quantity = 581265m
                        },
                        new
                        {
                            Id = 9,
                            InstrumentId = 8,
                            PortfolioId = 3,
                            Price = 103.48m,
                            Quantity = 466054m
                        },
                        new
                        {
                            Id = 10,
                            InstrumentId = 13,
                            PortfolioId = 4,
                            Price = 201.86m,
                            Quantity = 946508m
                        },
                        new
                        {
                            Id = 11,
                            InstrumentId = 2,
                            PortfolioId = 4,
                            Price = 311.84m,
                            Quantity = 126378m
                        },
                        new
                        {
                            Id = 12,
                            InstrumentId = 12,
                            PortfolioId = 5,
                            Price = 255.98m,
                            Quantity = 43448m
                        },
                        new
                        {
                            Id = 13,
                            InstrumentId = 30,
                            PortfolioId = 5,
                            Price = 335.75m,
                            Quantity = 351988m
                        },
                        new
                        {
                            Id = 14,
                            InstrumentId = 27,
                            PortfolioId = 5,
                            Price = 394.05m,
                            Quantity = 11064m
                        },
                        new
                        {
                            Id = 15,
                            InstrumentId = 28,
                            PortfolioId = 5,
                            Price = 62.28m,
                            Quantity = 639469m
                        },
                        new
                        {
                            Id = 16,
                            InstrumentId = 25,
                            PortfolioId = 6,
                            Price = 191.89m,
                            Quantity = 457567m
                        },
                        new
                        {
                            Id = 17,
                            InstrumentId = 7,
                            PortfolioId = 6,
                            Price = 343.56m,
                            Quantity = 599048m
                        },
                        new
                        {
                            Id = 18,
                            InstrumentId = 5,
                            PortfolioId = 6,
                            Price = 135.62m,
                            Quantity = 329285m
                        },
                        new
                        {
                            Id = 19,
                            InstrumentId = 18,
                            PortfolioId = 6,
                            Price = 332.54m,
                            Quantity = 666386m
                        },
                        new
                        {
                            Id = 20,
                            InstrumentId = 17,
                            PortfolioId = 7,
                            Price = 123.69m,
                            Quantity = 999736m
                        },
                        new
                        {
                            Id = 21,
                            InstrumentId = 27,
                            PortfolioId = 7,
                            Price = 244.34m,
                            Quantity = 443524m
                        },
                        new
                        {
                            Id = 22,
                            InstrumentId = 4,
                            PortfolioId = 7,
                            Price = 207.99m,
                            Quantity = 92144m
                        },
                        new
                        {
                            Id = 23,
                            InstrumentId = 29,
                            PortfolioId = 8,
                            Price = 82.27m,
                            Quantity = 842202m
                        },
                        new
                        {
                            Id = 24,
                            InstrumentId = 25,
                            PortfolioId = 8,
                            Price = 233.99m,
                            Quantity = 30847m
                        },
                        new
                        {
                            Id = 25,
                            InstrumentId = 9,
                            PortfolioId = 9,
                            Price = 273.73m,
                            Quantity = 899852m
                        },
                        new
                        {
                            Id = 26,
                            InstrumentId = 8,
                            PortfolioId = 9,
                            Price = 43.66m,
                            Quantity = 386897m
                        },
                        new
                        {
                            Id = 27,
                            InstrumentId = 3,
                            PortfolioId = 9,
                            Price = 119.64m,
                            Quantity = 678619m
                        },
                        new
                        {
                            Id = 28,
                            InstrumentId = 28,
                            PortfolioId = 9,
                            Price = 310.15m,
                            Quantity = 228857m
                        },
                        new
                        {
                            Id = 29,
                            InstrumentId = 8,
                            PortfolioId = 9,
                            Price = 125.26m,
                            Quantity = 106273m
                        },
                        new
                        {
                            Id = 30,
                            InstrumentId = 27,
                            PortfolioId = 10,
                            Price = 100.40m,
                            Quantity = 222843m
                        },
                        new
                        {
                            Id = 31,
                            InstrumentId = 3,
                            PortfolioId = 10,
                            Price = 323.47m,
                            Quantity = 151914m
                        });
                });

            modelBuilder.Entity("MyThinkBook.Web.Domain.Position", b =>
                {
                    b.HasOne("MyThinkBook.Web.Domain.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("position__instrument_fk");

                    b.HasOne("MyThinkBook.Web.Domain.Portfolio", null)
                        .WithMany("Positions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("portfolio__position_fk");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("MyThinkBook.Web.Domain.Portfolio", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
